/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lsp.liferay.portlet.advertising.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.lsp.liferay.portlet.advertising.model.CampaignLog;
import org.lsp.liferay.portlet.advertising.service.CampaignLocalService;
import org.lsp.liferay.portlet.advertising.service.CampaignLogLocalService;
import org.lsp.liferay.portlet.advertising.service.CampaignLogService;
import org.lsp.liferay.portlet.advertising.service.CampaignService;
import org.lsp.liferay.portlet.advertising.service.persistence.CampaignLogPersistence;
import org.lsp.liferay.portlet.advertising.service.persistence.CampaignPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the campaign log local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.lsp.liferay.portlet.advertising.service.impl.CampaignLogLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see org.lsp.liferay.portlet.advertising.service.impl.CampaignLogLocalServiceImpl
 * @see org.lsp.liferay.portlet.advertising.service.CampaignLogLocalServiceUtil
 * @generated
 */
public abstract class CampaignLogLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements CampaignLogLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.lsp.liferay.portlet.advertising.service.CampaignLogLocalServiceUtil} to access the campaign log local service.
	 */

	/**
	 * Adds the campaign log to the database. Also notifies the appropriate model listeners.
	 *
	 * @param campaignLog the campaign log
	 * @return the campaign log that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public CampaignLog addCampaignLog(CampaignLog campaignLog)
		throws SystemException {
		campaignLog.setNew(true);

		return campaignLogPersistence.update(campaignLog, false);
	}

	/**
	 * Creates a new campaign log with the primary key. Does not add the campaign log to the database.
	 *
	 * @param campaignLogId the primary key for the new campaign log
	 * @return the new campaign log
	 */
	public CampaignLog createCampaignLog(long campaignLogId) {
		return campaignLogPersistence.create(campaignLogId);
	}

	/**
	 * Deletes the campaign log with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param campaignLogId the primary key of the campaign log
	 * @return the campaign log that was removed
	 * @throws PortalException if a campaign log with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public CampaignLog deleteCampaignLog(long campaignLogId)
		throws PortalException, SystemException {
		return campaignLogPersistence.remove(campaignLogId);
	}

	/**
	 * Deletes the campaign log from the database. Also notifies the appropriate model listeners.
	 *
	 * @param campaignLog the campaign log
	 * @return the campaign log that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public CampaignLog deleteCampaignLog(CampaignLog campaignLog)
		throws SystemException {
		return campaignLogPersistence.remove(campaignLog);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(CampaignLog.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return campaignLogPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return campaignLogPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return campaignLogPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return campaignLogPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public CampaignLog fetchCampaignLog(long campaignLogId)
		throws SystemException {
		return campaignLogPersistence.fetchByPrimaryKey(campaignLogId);
	}

	/**
	 * Returns the campaign log with the primary key.
	 *
	 * @param campaignLogId the primary key of the campaign log
	 * @return the campaign log
	 * @throws PortalException if a campaign log with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public CampaignLog getCampaignLog(long campaignLogId)
		throws PortalException, SystemException {
		return campaignLogPersistence.findByPrimaryKey(campaignLogId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return campaignLogPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the campaign logs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of campaign logs
	 * @param end the upper bound of the range of campaign logs (not inclusive)
	 * @return the range of campaign logs
	 * @throws SystemException if a system exception occurred
	 */
	public List<CampaignLog> getCampaignLogs(int start, int end)
		throws SystemException {
		return campaignLogPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of campaign logs.
	 *
	 * @return the number of campaign logs
	 * @throws SystemException if a system exception occurred
	 */
	public int getCampaignLogsCount() throws SystemException {
		return campaignLogPersistence.countAll();
	}

	/**
	 * Updates the campaign log in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param campaignLog the campaign log
	 * @return the campaign log that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public CampaignLog updateCampaignLog(CampaignLog campaignLog)
		throws SystemException {
		return updateCampaignLog(campaignLog, true);
	}

	/**
	 * Updates the campaign log in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param campaignLog the campaign log
	 * @param merge whether to merge the campaign log with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the campaign log that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public CampaignLog updateCampaignLog(CampaignLog campaignLog, boolean merge)
		throws SystemException {
		campaignLog.setNew(false);

		return campaignLogPersistence.update(campaignLog, merge);
	}

	/**
	 * Returns the campaign local service.
	 *
	 * @return the campaign local service
	 */
	public CampaignLocalService getCampaignLocalService() {
		return campaignLocalService;
	}

	/**
	 * Sets the campaign local service.
	 *
	 * @param campaignLocalService the campaign local service
	 */
	public void setCampaignLocalService(
		CampaignLocalService campaignLocalService) {
		this.campaignLocalService = campaignLocalService;
	}

	/**
	 * Returns the campaign remote service.
	 *
	 * @return the campaign remote service
	 */
	public CampaignService getCampaignService() {
		return campaignService;
	}

	/**
	 * Sets the campaign remote service.
	 *
	 * @param campaignService the campaign remote service
	 */
	public void setCampaignService(CampaignService campaignService) {
		this.campaignService = campaignService;
	}

	/**
	 * Returns the campaign persistence.
	 *
	 * @return the campaign persistence
	 */
	public CampaignPersistence getCampaignPersistence() {
		return campaignPersistence;
	}

	/**
	 * Sets the campaign persistence.
	 *
	 * @param campaignPersistence the campaign persistence
	 */
	public void setCampaignPersistence(CampaignPersistence campaignPersistence) {
		this.campaignPersistence = campaignPersistence;
	}

	/**
	 * Returns the campaign log local service.
	 *
	 * @return the campaign log local service
	 */
	public CampaignLogLocalService getCampaignLogLocalService() {
		return campaignLogLocalService;
	}

	/**
	 * Sets the campaign log local service.
	 *
	 * @param campaignLogLocalService the campaign log local service
	 */
	public void setCampaignLogLocalService(
		CampaignLogLocalService campaignLogLocalService) {
		this.campaignLogLocalService = campaignLogLocalService;
	}

	/**
	 * Returns the campaign log remote service.
	 *
	 * @return the campaign log remote service
	 */
	public CampaignLogService getCampaignLogService() {
		return campaignLogService;
	}

	/**
	 * Sets the campaign log remote service.
	 *
	 * @param campaignLogService the campaign log remote service
	 */
	public void setCampaignLogService(CampaignLogService campaignLogService) {
		this.campaignLogService = campaignLogService;
	}

	/**
	 * Returns the campaign log persistence.
	 *
	 * @return the campaign log persistence
	 */
	public CampaignLogPersistence getCampaignLogPersistence() {
		return campaignLogPersistence;
	}

	/**
	 * Sets the campaign log persistence.
	 *
	 * @param campaignLogPersistence the campaign log persistence
	 */
	public void setCampaignLogPersistence(
		CampaignLogPersistence campaignLogPersistence) {
		this.campaignLogPersistence = campaignLogPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.lsp.liferay.portlet.advertising.model.CampaignLog",
			campaignLogLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.lsp.liferay.portlet.advertising.model.CampaignLog");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return CampaignLog.class;
	}

	protected String getModelClassName() {
		return CampaignLog.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = campaignLogPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CampaignLocalService.class)
	protected CampaignLocalService campaignLocalService;
	@BeanReference(type = CampaignService.class)
	protected CampaignService campaignService;
	@BeanReference(type = CampaignPersistence.class)
	protected CampaignPersistence campaignPersistence;
	@BeanReference(type = CampaignLogLocalService.class)
	protected CampaignLogLocalService campaignLogLocalService;
	@BeanReference(type = CampaignLogService.class)
	protected CampaignLogService campaignLogService;
	@BeanReference(type = CampaignLogPersistence.class)
	protected CampaignLogPersistence campaignLogPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private CampaignLogLocalServiceClpInvoker _clpInvoker = new CampaignLogLocalServiceClpInvoker();
}