/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lsp.liferay.portlet.advertising.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Campaign service. Represents a row in the &quot;LSPAC_Campaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lsp.liferay.portlet.advertising.model.impl.CampaignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lsp.liferay.portlet.advertising.model.impl.CampaignImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Campaign
 * @see org.lsp.liferay.portlet.advertising.model.impl.CampaignImpl
 * @see org.lsp.liferay.portlet.advertising.model.impl.CampaignModelImpl
 * @generated
 */
public interface CampaignModel extends BaseModel<Campaign> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a campaign model instance should use the {@link Campaign} interface instead.
	 */

	/**
	 * Returns the primary key of this campaign.
	 *
	 * @return the primary key of this campaign
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this campaign.
	 *
	 * @param primaryKey the primary key of this campaign
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this campaign.
	 *
	 * @return the company ID of this campaign
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this campaign.
	 *
	 * @param companyId the company ID of this campaign
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the campaign ID of this campaign.
	 *
	 * @return the campaign ID of this campaign
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this campaign.
	 *
	 * @param campaignId the campaign ID of this campaign
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Returns the journal article primary key of this campaign.
	 *
	 * @return the journal article primary key of this campaign
	 */
	public long getJournalArticlePrimaryKey();

	/**
	 * Sets the journal article primary key of this campaign.
	 *
	 * @param journalArticlePrimaryKey the journal article primary key of this campaign
	 */
	public void setJournalArticlePrimaryKey(long journalArticlePrimaryKey);

	/**
	 * Returns the begin date of this campaign.
	 *
	 * @return the begin date of this campaign
	 */
	public Date getBeginDate();

	/**
	 * Sets the begin date of this campaign.
	 *
	 * @param beginDate the begin date of this campaign
	 */
	public void setBeginDate(Date beginDate);

	/**
	 * Returns the end date of this campaign.
	 *
	 * @return the end date of this campaign
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this campaign.
	 *
	 * @param endDate the end date of this campaign
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the campaign status of this campaign.
	 *
	 * @return the campaign status of this campaign
	 */
	public int getCampaignStatus();

	/**
	 * Sets the campaign status of this campaign.
	 *
	 * @param campaignStatus the campaign status of this campaign
	 */
	public void setCampaignStatus(int campaignStatus);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Campaign campaign);

	public int hashCode();

	public CacheModel<Campaign> toCacheModel();

	public Campaign toEscapedModel();

	public String toString();

	public String toXmlString();
}